update name in readme.md
zoop/zoop-gateway-ios-sdk pull request #2
Opened 2020-06-11 09:59 UTC by divyank96

correct the name from android to ios

2020-06-12 12:38 UTC, iAziz786 requested changes

2020-06-12 12:38 UTC, iAziz786 commented on Readme.md
>  AadhaarAPI | Zoop Android SDK for Income Tax Return and Bank Statement Analysis Gateway
> AadhaarAPI | Zoop Android SDK for Income Tax Return and Bank Statement Analysis Gateway

This text should also change right?

2020-06-12 15:12 UTC, iAziz786 approved these changes
LGMT

2020-06-16 06:56 UTC, thefoodiecoder approved these changes

2020-06-16 06:56 UTC, merged